### ISSUE TITLE
SWI-Prolog v.8.1.0 on Termux: libreadline.so.7 not found

### ISSUE THREAD

**Issue by BernardMarsh** [erlanger/swipl-termux#2]
Trying to run swipl on the latest version of Termux (android 8.0.1) gives the error "libreadline.so.7 not found". It seems that Termux now has readline 8.0 and package version 7 is not available.

**Comment by erlanger** [comment]
Thanks, I'll update it asap. Was there any other library not found?

**Comment by erlanger** [comment]
@BernardMarsh, pushed a new version. Please test it, and let me know.

**Comment by BernardMarsh** [comment]
Quick test: all seems to be working ok now.
Many thanks - for this and all the great work!
Bernard

----- Original Message -----

**Comment by erlanger** [comment]
Thanks!
